### ISSUE TITLE
Используй SpringBootTest

### ISSUE THREAD

**Issue by GordPavel** [grigory-pc/java-filmorate#2]
https://github.com/grigory-pc/java-filmorate/blob/330ad4eefe599072aba2fb2349dbafcd54406531/src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java#L22
Запустил тесты – они не работают, если заранее не запустить сервер отдельно. Не надо так делать, на вебинарах показывал, как пользоваться `SrpginBootTest` для контроллеров

**Comment by grigory-pc** [comment]
Я начал делать проект до того, как успел посмотреть запись вебинара. Попробую доработать в этой части. Спасибо!)

**Comment by grigory-pc** [comment]
Поставил аннотацию, но с `defined port`. Теперь всё работает без отдельного запуска севера. Удобно).
Спасибо!
