### ISSUE TITLE
Не кидаешь исключение

### ISSUE THREAD

**Issue by GordPavel** [grigory-pc/java-filmorate#3]
https://github.com/grigory-pc/java-filmorate/blob/330ad4eefe599072aba2fb2349dbafcd54406531/src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java#L44
Тут твое исключение об ошибке проглатывается и никуда не отправляется. Если хочешь логгировать исключение и отправлять его, то сделай 
```java
log.warn(e.getMessage());
throw e;
```

**Comment by grigory-pc** [comment]
Супер! Это помогло. Спасибо!) Я ещё раз посмотрел теорию про исключения, но не нашел такой конструкции, только создание нового исключения через `throw new`
