### ISSUE TITLE
Очищать состояние между тестами

### ISSUE THREAD

**Issue by GordPavel** [grigory-pc/java-filmorate#4]
https://github.com/grigory-pc/java-filmorate/blob/330ad4eefe599072aba2fb2349dbafcd54406531/src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java#L42
Сейчас у тебя между тестами сохраняется состояние. Так делать не нужно. Воспользуйся `SpringBootTest` и я показывал на вебинаре, как можно очищать хранилище между тестами. Иначе у тебя странно, что несколько фильмов сохраняются с одинаковыми id=0 и никакой ошибки из-за этого нет

**Comment by grigory-pc** [comment]
Так это же список, а не мапа. Тут можно спокойно одинаковые объекты сохранять. Разве нет?
Но замечание понял. Внесу корректировки)

**Comment by grigory-pc** [comment]
Не нашел в записи вебинара про очистку между методами, но нагуглил вот такую аннотацию:
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)

Теперь перед каждым тестом автоматически перезапускается сервер и, соответственно, контекст чистится.
