### ISSUE TITLE
Несколько проверок

### ISSUE THREAD

**Issue by GordPavel** [grigory-pc/java-filmorate#5]
https://github.com/grigory-pc/java-filmorate/blob/330ad4eefe599072aba2fb2349dbafcd54406531/src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java#L33
Я показывал на вебинаре, как можно выполнить проверку с помощью списка предикатов и stream. Воспользуйся этим подходом

**Comment by grigory-pc** [comment]
Посмотрю, попробую. Спасибо.

**Comment by grigory-pc** [comment]
Посмотрел несколько раз, попробовал, но для меня это сложновато. Когда пытался сделать аналогию, то было ощущение, что я не понимаю что делаю и не понимаю как это работает. На вебинаре недостаточно подробно объяснялась логика и последовательность работы, во всяком случае для меня. Или слишком быстро это проговорилось. Даже останавливая запись, не усваивается у меня. Всё-таки это материал, эта методика пока сложная. Хотя визуально выглядит лаконичнее и практичнее. Возможно дальше по заданиям попробую или факультативно буду дальше изучать и тестировать.
